import { v0_8 } from "@a2ui/lit";

const empty = {} as Record<string, boolean>;
const emptyStringArray: string[] = [];

export const minimalTheme: v0_8.Types.Theme = {
  components: {
    AudioPlayer: empty,
    Button: empty,
    Card: empty,
    Column: empty,
    CheckBox: { container: empty, element: empty, label: empty },
    DateTimeInput: { container: empty, element: empty, label: empty },
    Divider: empty,
    Image: {
      all: empty,
      icon: empty,
      avatar: empty,
      smallFeature: empty,
      mediumFeature: empty,
      largeFeature: empty,
      header: empty,
    },
    Icon: empty,
    List: empty,
    Modal: { backdrop: empty, element: empty },
    MultipleChoice: { container: empty, element: empty, label: empty },
    Row: empty,
    Slider: { container: empty, element: empty, label: empty },
    Tabs: {
      container: empty,
      element: empty,
      controls: { all: empty, selected: empty },
    },
    Text: {
      all: empty,
      h1: empty,
      h2: empty,
      h3: empty,
      h4: empty,
      h5: empty,
      caption: empty,
      body: empty,
    },
    TextField: { container: empty, element: empty, label: empty },
    Video: empty,
  },
  elements: {
    a: empty,
    audio: empty,
    body: empty,
    button: empty,
    h1: empty,
    h2: empty,
    h3: empty,
    h4: empty,
    h5: empty,
    iframe: empty,
    input: empty,
    p: empty,
    pre: empty,
    textarea: empty,
    video: empty,
  },
  markdown: {
    p: emptyStringArray,
    h1: emptyStringArray,
    h2: emptyStringArray,
    h3: emptyStringArray,
    h4: emptyStringArray,
    h5: emptyStringArray,
    ul: emptyStringArray,
    ol: emptyStringArray,
    li: emptyStringArray,
    a: emptyStringArray,
    strong: emptyStringArray,
    em: emptyStringArray,
  },
  additionalStyles: {},
};
